# ==============================================================================
# Pathway Similarity Analysis via Jaccard Index (Base R Version)
# ==============================================================================
# Analyzes gene overlap between enriched pathways using Jaccard similarity
# Creates clustered heatmaps and identifies hub genes (appearing in many pathways)
#
# Produces:
#   - Tables 2, 3: gene_pathway_counts.csv (filtered for inflammation/ECM themes)
#   - pathway_similarity_heatmap.pdf
#   - pathway_hub_genes.pdf/.csv
#   - pathway_similarity_distribution.pdf
#
# USAGE:
#   source(here("analysis", "04_pathway", "analyze_pathway_similarity.R"))
#
# Requires:
#   - Input: results/04_pathway/major/stringent/CF_major_stringent_disease_relevant_pathways.csv
#     (generated by run_all_analyses.R → run_analysis("C"))
# ==============================================================================

library(here)

# ==============================================================================
# CORE FUNCTIONS
# ==============================================================================

#' Calculate Jaccard Index between two sets
calc_jaccard <- function(set1, set2) {
  set1 <- unique(set1)
  set2 <- unique(set2)
  
  if (length(set1) == 0 && length(set2) == 0) return(NA_real_)
  
  intersection <- length(intersect(set1, set2))
  union_size <- length(union(set1, set2))
  
  if (union_size == 0) return(0)
  return(intersection / union_size)
}


#' Parse gene IDs from pathway data
parse_genes <- function(gene_string, delimiter = "/") {
  if (is.na(gene_string) || gene_string == "") {
    return(character(0))
  }
  genes <- unlist(strsplit(gene_string, delimiter, fixed = TRUE))
  genes <- trimws(genes)
  genes <- genes[genes != ""]
  return(unique(genes))
}


#' Extract gene sets for each pathway from enrichment results
get_pathway_gene_sets <- function(df, 
                                   pathway_col = "ID",
                                   gene_col = "geneID",
                                   description_col = "Description",
                                   delimiter = "/",
                                   max_label_length = 50) {
  
  # Create pathway labels (ID: Description for readability)
  desc_truncated <- substr(df[[description_col]], 1, max_label_length)
  pathway_labels <- paste0(df[[pathway_col]], ": ", desc_truncated)
  
  # Extract gene sets
  gene_sets <- lapply(df[[gene_col]], function(g) {
    parse_genes(g, delimiter)
  })
  
  names(gene_sets) <- pathway_labels
  
  return(gene_sets)
}


#' Calculate pairwise Jaccard matrix for all pathway gene sets
calc_pairwise_jaccard <- function(gene_sets, progress = TRUE) {
  
  pathways <- names(gene_sets)
  n <- length(pathways)
  
  if (progress) {
    cat(sprintf("Calculating pairwise Jaccard for %d pathways (%d comparisons)...\n",
                n, n * (n - 1) / 2))
  }
  
  # Initialize matrices
  jaccard_mat <- matrix(NA_real_, nrow = n, ncol = n,
                        dimnames = list(pathways, pathways))
  intersection_mat <- matrix(0L, nrow = n, ncol = n,
                             dimnames = list(pathways, pathways))
  
  # Calculate pairwise metrics
  for (i in seq_len(n)) {
    for (j in seq_len(n)) {
      set_i <- gene_sets[[i]]
      set_j <- gene_sets[[j]]
      
      jaccard_mat[i, j] <- calc_jaccard(set_i, set_j)
      intersection_mat[i, j] <- length(intersect(set_i, set_j))
    }
    
    if (progress && i %% 20 == 0) {
      cat(sprintf("  Processed %d/%d pathways\n", i, n))
    }
  }
  
  if (progress) cat("  Done.\n\n")
  
  return(list(
    jaccard = jaccard_mat,
    intersection = intersection_mat
  ))
}


#' Identify hub genes appearing in many pathways
find_hub_genes <- function(gene_sets, min_pathways = 3) {
  
  # Count pathway membership for each gene
  all_genes <- unique(unlist(gene_sets))
  pathway_names <- names(gene_sets)
  
  gene_data <- lapply(all_genes, function(gene) {
    in_pathways <- sapply(gene_sets, function(gs) gene %in% gs)
    which_pathways <- pathway_names[in_pathways]
    
    data.frame(
      Gene = gene,
      Pathway_Count = sum(in_pathways),
      Pathways = paste(which_pathways, collapse = "; "),
      stringsAsFactors = FALSE
    )
  })
  
  gene_df <- do.call(rbind, gene_data)
  gene_df <- gene_df[gene_df$Pathway_Count >= min_pathways, ]
  gene_df <- gene_df[order(-gene_df$Pathway_Count), ]
  rownames(gene_df) <- NULL
  
  return(gene_df)
}


#' Get complete gene-pathway membership table
get_gene_pathway_membership <- function(gene_sets) {
  
  all_genes <- sort(unique(unlist(gene_sets)))
  pathway_labels <- names(gene_sets)
  
  membership_list <- lapply(all_genes, function(gene) {
    in_pathways <- sapply(gene_sets, function(gs) gene %in% gs)
    
    if (sum(in_pathways) > 0) {
      data.frame(
        Gene = gene,
        Pathway = pathway_labels[in_pathways],
        stringsAsFactors = FALSE
      )
    } else {
      NULL
    }
  })
  
  membership_df <- do.call(rbind, membership_list)
  rownames(membership_df) <- NULL
  
  return(membership_df)
}


#' Get gene summary with pathway counts
get_gene_summary <- function(gene_sets) {
  
  all_genes <- unique(unlist(gene_sets))
  
  counts <- sapply(all_genes, function(gene) {
    sum(sapply(gene_sets, function(gs) gene %in% gs))
  })
  
  gene_summary <- data.frame(
    Gene = all_genes,
    Pathway_Count = counts,
    stringsAsFactors = FALSE
  )
  
  gene_summary <- gene_summary[order(-gene_summary$Pathway_Count), ]
  rownames(gene_summary) <- NULL
  
  return(gene_summary)
}


# ==============================================================================
# VISUALIZATION FUNCTIONS
# ==============================================================================

#' Create clustered heatmap of pathway similarity
plot_pathway_heatmap <- function(jaccard_matrix,
                                  title = "Pathway Similarity (Jaccard Index)",
                                  output_file = NULL,
                                  width = 14,
                                  height = 12,
                                  cex_row = 0.4,
                                  cex_col = 0.4,
                                  margins = c(12, 12)) {
  
  # Color palette (white to red)
  colors <- colorRampPalette(c("white", "lightyellow", "orange", "red", "darkred"))(100)
  
  # Open PDF if output file specified
  if (!is.null(output_file)) {
    pdf(output_file, width = width, height = height)
  }
  
  # Create heatmap
  heatmap(
    jaccard_matrix,
    col = colors,
    scale = "none",
    symm = TRUE,
    margins = margins,
    cexRow = cex_row,
    cexCol = cex_col,
    main = title
  )
  
  if (!is.null(output_file)) {
    dev.off()
  }
}


#' Create bar plot of hub genes
plot_hub_genes <- function(hub_genes, 
                            top_n = 30,
                            output_file = NULL,
                            width = 10,
                            height = 10) {
  
  # Get top genes
  plot_data <- head(hub_genes, top_n)
  
  if (!is.null(output_file)) {
    pdf(output_file, width = width, height = height)
  }
  
  # Set up margins
  par(mar = c(5, 12, 4, 2))
  
  # Create horizontal bar plot
  barplot(
    rev(plot_data$Pathway_Count),
    names.arg = rev(plot_data$Gene),
    horiz = TRUE,
    las = 1,
    col = "steelblue",
    xlab = "Number of Pathways",
    main = sprintf("Hub Genes (Present in >= %d Pathways)", min(plot_data$Pathway_Count)),
    cex.names = 0.7
  )
  
  par(mar = c(5, 4, 4, 2))  # Reset margins
  
  if (!is.null(output_file)) {
    dev.off()
  }
}


#' Create histogram of similarity distribution
plot_similarity_distribution <- function(jaccard_matrix,
                                          output_file = NULL,
                                          width = 8,
                                          height = 6) {
  
  # Extract upper triangle (excluding diagonal)
  upper_tri <- jaccard_matrix[upper.tri(jaccard_matrix)]
  
  # Summary stats
  mean_jac <- mean(upper_tri, na.rm = TRUE)
  median_jac <- median(upper_tri, na.rm = TRUE)
  
  if (!is.null(output_file)) {
    pdf(output_file, width = width, height = height)
  }
  
  hist(
    upper_tri,
    breaks = 50,
    col = "steelblue",
    border = "white",
    main = "Distribution of Pathway Similarities",
    xlab = "Jaccard Index",
    ylab = "Frequency",
    xlim = c(0, max(upper_tri, na.rm = TRUE) * 1.1)
  )
  
  # Add mean and median lines
  abline(v = mean_jac, col = "red", lwd = 2, lty = 2)
  abline(v = median_jac, col = "darkgreen", lwd = 2, lty = 2)
  
  # Add legend
  legend(
    "topright",
    legend = c(sprintf("Mean: %.3f", mean_jac),
               sprintf("Median: %.3f", median_jac)),
    col = c("red", "darkgreen"),
    lwd = 2,
    lty = 2,
    bty = "n"
  )
  
  if (!is.null(output_file)) {
    dev.off()
  }
}


# ==============================================================================
# MAIN ANALYSIS FUNCTION
# ==============================================================================

#' Analyze pathway similarity
#' 
#' @param input_file Path to CSV file with pathway enrichment results
#' @param output_dir Output directory for results
#' @param pathway_col Column name for pathway IDs
#' @param gene_col Column name for gene IDs
#' @param description_col Column name for pathway descriptions
#' @param database_col Column name for database source (optional)
#' @param delimiter Gene ID delimiter
#' @param top_n_pathways Limit analysis to top N pathways (NULL = all)
#' @param min_hub_pathways Minimum pathways for hub gene classification
#' @param qvalue_col Column for significance filtering
#' @param max_qvalue Maximum q-value threshold
#' @param save_outputs Save results to files
#' @param verbose Print progress messages
#' @return List with analysis results
analyze_pathway_similarity <- function(
    input_file,
    output_dir = "pathway_similarity_results",
    pathway_col = "ID",
    gene_col = "geneID",
    description_col = "Description",
    database_col = "Database",
    delimiter = "/",
    top_n_pathways = NULL,
    min_hub_pathways = 5,
    qvalue_col = "qvalue",
    max_qvalue = 0.05,
    save_outputs = TRUE,
    verbose = TRUE
) {
  
  # --------------------------------------------------------------------------
  # Setup
  # --------------------------------------------------------------------------
  
  if (verbose) {
    cat("\n")
    cat("================================================================================\n")
    cat("                    PATHWAY SIMILARITY ANALYSIS                                 \n")
    cat("================================================================================\n\n")
  }
  
  # Create output directory
  if (save_outputs && !dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    if (verbose) cat(sprintf("Created output directory: %s\n\n", output_dir))
  }
  
  # --------------------------------------------------------------------------
  # Load and process data
  # --------------------------------------------------------------------------
  
  if (verbose) cat("Loading pathway data...\n")
  
  df <- read.csv(input_file, stringsAsFactors = FALSE)
  
  if (verbose) {
    cat(sprintf("  Loaded %d pathways from %s\n", nrow(df), basename(input_file)))
  }
  
  # Filter by significance if column exists
  if (qvalue_col %in% names(df)) {
    df_sig <- df[df[[qvalue_col]] <= max_qvalue, ]
    if (verbose) {
      cat(sprintf("  Filtered to %d significant pathways (q <= %.2f)\n", 
                  nrow(df_sig), max_qvalue))
    }
  } else {
    df_sig <- df
  }
  
  # Limit to top N if specified
  if (!is.null(top_n_pathways) && nrow(df_sig) > top_n_pathways) {
    df_sig <- df_sig[1:top_n_pathways, ]
    if (verbose) {
      cat(sprintf("  Limited to top %d pathways\n", top_n_pathways))
    }
  }
  
  n_pathways <- nrow(df_sig)
  
  if (verbose) cat("\n")
  
  # --------------------------------------------------------------------------
  # Extract gene sets
  # --------------------------------------------------------------------------
  
  if (verbose) cat("Extracting pathway gene sets...\n")
  
  gene_sets <- get_pathway_gene_sets(
    df_sig,
    pathway_col = pathway_col,
    gene_col = gene_col,
    description_col = description_col,
    delimiter = delimiter
  )
  
  # Summary statistics
  gene_counts <- sapply(gene_sets, length)
  all_genes <- unique(unlist(gene_sets))
  n_unique_genes <- length(all_genes)
  
  if (verbose) {
    cat(sprintf("  %d pathways with %d unique genes total\n", n_pathways, n_unique_genes))
    cat(sprintf("  Genes per pathway: median = %.0f, range = %d-%d\n\n",
                median(gene_counts), min(gene_counts), max(gene_counts)))
  }
  
  # --------------------------------------------------------------------------
  # Calculate pairwise Jaccard
  # --------------------------------------------------------------------------
  
  pairwise_results <- calc_pairwise_jaccard(gene_sets, progress = verbose)
  jaccard_matrix <- pairwise_results$jaccard
  
  # Summary of similarities
  upper_tri <- jaccard_matrix[upper.tri(jaccard_matrix)]
  
  if (verbose) {
    cat("Jaccard similarity summary:\n")
    cat(sprintf("  Mean: %.3f\n", mean(upper_tri, na.rm = TRUE)))
    cat(sprintf("  Median: %.3f\n", median(upper_tri, na.rm = TRUE)))
    cat(sprintf("  Max: %.3f\n", max(upper_tri, na.rm = TRUE)))
    cat(sprintf("  Pairs with Jaccard >= 0.3: %d (%.1f%%)\n",
                sum(upper_tri >= 0.3, na.rm = TRUE),
                100 * sum(upper_tri >= 0.3, na.rm = TRUE) / length(upper_tri)))
    cat("\n")
  }
  
  # --------------------------------------------------------------------------
  # Find hub genes
  # --------------------------------------------------------------------------
  
  if (verbose) cat("Identifying hub genes...\n")
  
  hub_genes <- find_hub_genes(gene_sets, min_pathways = min_hub_pathways)
  
  if (verbose) {
    cat(sprintf("  Found %d genes appearing in >= %d pathways\n",
                nrow(hub_genes), min_hub_pathways))
    if (nrow(hub_genes) > 0) {
      cat(sprintf("  Top hub gene: %s (%d pathways)\n",
                  hub_genes$Gene[1], hub_genes$Pathway_Count[1]))
    }
    cat("\n")
  }
  
  # Get detailed gene-pathway membership
  membership <- get_gene_pathway_membership(gene_sets)
  
  # Get gene summary
  gene_summary <- get_gene_summary(gene_sets)
  
  # --------------------------------------------------------------------------
  # Hierarchical clustering
  # --------------------------------------------------------------------------
  
  if (verbose) cat("Performing hierarchical clustering...\n")
  
  # Distance matrix (1 - Jaccard = dissimilarity)
  dist_matrix <- as.dist(1 - jaccard_matrix)
  hc <- hclust(dist_matrix, method = "complete")
  
  # Cut tree at different heights to get cluster assignments
  n_clusters <- max(2, round(sqrt(n_pathways)))
  clusters <- cutree(hc, k = n_clusters)
  
  cluster_df <- data.frame(
    Pathway = names(gene_sets),
    Cluster = clusters,
    stringsAsFactors = FALSE
  )
  cluster_df <- cluster_df[order(cluster_df$Cluster), ]
  rownames(cluster_df) <- NULL
  
  if (verbose) {
    cat(sprintf("  Created %d clusters\n\n", n_clusters))
  }
  
  # --------------------------------------------------------------------------
  # Save outputs
  # --------------------------------------------------------------------------
  
  if (save_outputs) {
    if (verbose) cat("Saving outputs...\n")
    
    # Jaccard matrix
    jaccard_df <- as.data.frame(jaccard_matrix)
    jaccard_df$Pathway <- rownames(jaccard_df)
    jaccard_df <- jaccard_df[, c("Pathway", setdiff(names(jaccard_df), "Pathway"))]
    write.csv(jaccard_df,
              file.path(output_dir, "pathway_jaccard_matrix.csv"),
              row.names = FALSE)
    if (verbose) cat("  - pathway_jaccard_matrix.csv\n")
    
    # Hub genes
    write.csv(hub_genes,
              file.path(output_dir, "pathway_hub_genes.csv"),
              row.names = FALSE)
    if (verbose) cat("  - pathway_hub_genes.csv\n")
    
    # Full gene summary (source for Tables 2, 3)
    write.csv(gene_summary,
              file.path(output_dir, "gene_pathway_counts.csv"),
              row.names = FALSE)
    if (verbose) cat("  - gene_pathway_counts.csv (source for Tables 2, 3)\n")
    
    # Gene-pathway membership (detailed)
    write.csv(membership,
              file.path(output_dir, "gene_pathway_membership.csv"),
              row.names = FALSE)
    if (verbose) cat("  - gene_pathway_membership.csv\n")
    
    # Cluster assignments
    write.csv(cluster_df,
              file.path(output_dir, "pathway_clusters.csv"),
              row.names = FALSE)
    if (verbose) cat("  - pathway_clusters.csv\n")
    
    # Create visualizations
    if (verbose) cat("\nCreating visualizations...\n")
    
    # Adjust sizes based on pathway count
    hm_width <- max(14, n_pathways * 0.15)
    hm_height <- max(12, n_pathways * 0.12)
    cex_labels <- max(0.3, 0.8 - n_pathways * 0.003)
    
    # Clustered heatmap
    plot_pathway_heatmap(
      jaccard_matrix,
      title = "Pathway Similarity (Jaccard Index)",
      output_file = file.path(output_dir, "pathway_similarity_heatmap.pdf"),
      width = hm_width,
      height = hm_height,
      cex_row = cex_labels,
      cex_col = cex_labels
    )
    if (verbose) cat("  - pathway_similarity_heatmap.pdf\n")
    
    # Hub genes plot
    if (nrow(hub_genes) > 0) {
      plot_hub_genes(
        hub_genes, 
        top_n = min(40, nrow(hub_genes)),
        output_file = file.path(output_dir, "pathway_hub_genes.pdf")
      )
      if (verbose) cat("  - pathway_hub_genes.pdf\n")
    }
    
    # Similarity distribution
    plot_similarity_distribution(
      jaccard_matrix,
      output_file = file.path(output_dir, "pathway_similarity_distribution.pdf")
    )
    if (verbose) cat("  - pathway_similarity_distribution.pdf\n")
  }
  
  # --------------------------------------------------------------------------
  # Return results
  # --------------------------------------------------------------------------
  
  if (verbose) {
    cat("\n")
    cat("================================================================================\n")
    cat("                         ANALYSIS COMPLETE                                      \n")
    cat("================================================================================\n\n")
    
    cat("KEY FINDINGS:\n")
    cat(sprintf("  - %d pathways analyzed with %d unique genes\n", n_pathways, n_unique_genes))
    cat(sprintf("  - Mean pairwise similarity: %.3f (Jaccard)\n", mean(upper_tri, na.rm = TRUE)))
    cat(sprintf("  - %d hub genes appear in >= %d pathways\n", nrow(hub_genes), min_hub_pathways))
    if (nrow(hub_genes) >= 5) {
      top5 <- head(hub_genes, 5)
      cat(sprintf("  - Top hub genes: %s\n", 
                  paste(sprintf("%s (%d)", top5$Gene, top5$Pathway_Count), collapse = ", ")))
    }
    cat("\n")
  }
  
  results <- list(
    # Input info
    input_file = input_file,
    n_pathways = n_pathways,
    n_unique_genes = n_unique_genes,
    
    # Pathway data
    pathway_data = df_sig,
    gene_sets = gene_sets,
    
    # Jaccard analysis
    jaccard_matrix = jaccard_matrix,
    intersection_matrix = pairwise_results$intersection,
    
    # Clustering
    hclust = hc,
    clusters = cluster_df,
    
    # Hub genes
    hub_genes = hub_genes,
    gene_summary = gene_summary,
    gene_pathway_membership = membership,
    
    # Summary stats
    summary = list(
      mean_jaccard = mean(upper_tri, na.rm = TRUE),
      median_jaccard = median(upper_tri, na.rm = TRUE),
      max_jaccard = max(upper_tri, na.rm = TRUE),
      n_high_similarity = sum(upper_tri >= 0.3, na.rm = TRUE)
    )
  )
  
  class(results) <- c("pathway_similarity_analysis", class(results))
  
  invisible(results)
}


#' Print method for pathway_similarity_analysis objects
print.pathway_similarity_analysis <- function(x, ...) {
  cat("Pathway Similarity Analysis\n")
  cat("===========================\n")
  cat(sprintf("Pathways: %d\n", x$n_pathways))
  cat(sprintf("Unique genes: %d\n", x$n_unique_genes))
  cat(sprintf("Mean Jaccard: %.3f\n", x$summary$mean_jaccard))
  cat(sprintf("Hub genes (>=5 pathways): %d\n", nrow(x$hub_genes)))
  cat("\nUse $ to access: jaccard_matrix, hub_genes, clusters, gene_summary\n")
}


# ==============================================================================
# RUN ANALYSIS
# ==============================================================================

# Input and output paths using here()
input_file <- here("results", "04_pathway", "major", "stringent", 
                   "CF_major_stringent_disease_relevant_pathways.csv")
output_dir <- here("results", "04_pathway", "major", "stringent", 
                   "pathway_similarity_results")

# Verify input file exists
if (!file.exists(input_file)) {
  stop("Input file not found: ", input_file, "\n",
       "Run run_analysis('C') first to generate disease-relevant pathways.")
}

# Run the analysis
results <- analyze_pathway_similarity(
  input_file = input_file,
  top_n_pathways = NULL,
  min_hub_pathways = 5,
  output_dir = output_dir
)

cat("\n=== analyze_pathway_similarity.R complete ===\n")
cat("Tables 2 & 3 source: ", file.path(output_dir, "gene_pathway_counts.csv"), "\n")
cat("(Filter for inflammation or ECM/TGF-β themes; Function column is AI-curated)\n\n")
