# ==============================================================================
# Categorize Enriched Pathways by Biological Theme
# ==============================================================================
# Groups pathway enrichment results into major biological categories
# Creates summary visualization
#
# Produces:
#   - Fig 5C: pathway_categories_stacked_barplot.png
#   - Table 1: pathway_categories_summary.csv
#
# Usage:
#   source(here("analysis", "04_pathway", "categorize_pathways.R"))
#
# Requires:
#   - Input: results/04_pathway/major/stringent/CF_major_stringent_disease_relevant_pathways.csv
#     (generated by run_all_analyses.R)
# ==============================================================================

library(here)

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

input_file <- here("results", "04_pathway", "major", "stringent", 
                   "CF_major_stringent_disease_relevant_pathways.csv")
output_dir <- here("results", "04_pathway")
qvalue_threshold <- 0.05
output_prefix <- file.path(output_dir, "pathway_categories")

# Create output directory if needed
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

# ------------------------------------------------------------------------------
# Verify input file exists
# ------------------------------------------------------------------------------

if (!file.exists(input_file)) {
  stop("Input file not found: ", input_file, "\n",
       "Run run_all_analyses.R first to generate pathway enrichment results.")
}

# ------------------------------------------------------------------------------
# Define pathway categories with search patterns
# ------------------------------------------------------------------------------

categories <- list(
  "T Cell Regulation" = c("T cell", "T-cell", "alpha-beta T", "CD4", "CD8", "Th17", 
                          "T-helper", "regulatory T cell", "thymocyte"),
  "Epithelial/Tissue" = c("epithelial", "epithelium", "mesenchymal transition", "EMT",
                          "wound healing", "cell spreading", "cell migration", "cell motility"),
  "Cytokine Production" = c("interleukin", "interferon", "TNF", "tumor necrosis factor", 
                            "cytokine production"),
  "TLR/Innate Sensing" = c("toll-like", "toll like", "TLR", "innate immune", "bacterial origin",
                           "NLRP", "inflammasome"),
  "TGF-beta/ECM/Fibrosis" = c("TGF-beta", "TGF-β", "fibroblast", "collagen", "extracellular matrix", 
                              "ECM", "matrix"),
  "NF-kB/MAPK Signaling" = c("NF-kappaB", "NFkB", "NF-kB", "MAPK", "MAP kinase"),
  "Viral Infection" = c("virus", "viral", "herpes", "cytomegalovirus", "papillomavirus", 
                        "Epstein-Barr", "HIV", "HTLV", "Kaposi"),
  "Bacterial Infection" = c("Salmonella", "Yersinia"),
  "B Cell/Humoral" = c("B cell", "B-cell", "immunoglobulin"),
  "Myeloid/DC/Macrophage" = c("macrophage", "dendritic cell", "myeloid", "NK cell", "natural killer")
)

# ------------------------------------------------------------------------------
# Load and filter data
# ------------------------------------------------------------------------------

df <- read.csv(input_file, stringsAsFactors = FALSE)
sig <- df[df$qvalue < qvalue_threshold, ]

cat(sprintf("Loaded %d pathways, %d significant (q < %g)\n\n", 
            nrow(df), nrow(sig), qvalue_threshold))

# ------------------------------------------------------------------------------
# Categorize pathways
# ------------------------------------------------------------------------------

# Count pathways per category
category_counts <- sapply(names(categories), function(cat_name) {
  patterns <- categories[[cat_name]]
  sum(sapply(sig$Description, function(desc) {
    any(sapply(patterns, function(p) grepl(p, desc, ignore.case = TRUE)))
  }))
})

# Sort by count
category_counts <- sort(category_counts, decreasing = TRUE)

# Print summary
cat("=== PATHWAY CATEGORY SUMMARY ===\n\n")
for (i in seq_along(category_counts)) {
  cat(sprintf("%-25s %3d pathways\n", names(category_counts)[i], category_counts[i]))
}
cat(sprintf("\nTotal unique pathways: %d\n", nrow(sig)))
cat("(Note: some pathways may fit multiple categories)\n\n")

# ------------------------------------------------------------------------------
# Create visualization - Simple version
# ------------------------------------------------------------------------------

create_plot <- function() {
  par(mar = c(5, 12, 4, 2))
  
  barplot(
    rev(category_counts),
    names.arg = rev(names(category_counts)),
    horiz = TRUE,
    las = 1,
    col = "steelblue",
    border = NA,
    xlim = c(0, max(category_counts) * 1.05),
    xlab = "Number of Pathways",
    main = "CF-Relevant Pathway Categories",
    cex.names = 0.9,
    cex.lab = 1.1,
    cex.main = 1.2
  )
  
  mtext(paste0("q < ", qvalue_threshold), side = 3, line = 0.3, cex = 0.9, col = "gray40")
}

# Save PDF
pdf(paste0(output_prefix, "_barplot.pdf"), width = 10, height = 7)
create_plot()
dev.off()

# Save PNG
png(paste0(output_prefix, "_barplot.png"), width = 10, height = 7, units = "in", res = 300)
create_plot()
dev.off()

cat("Simple barplots saved to:", paste0(output_prefix, "_barplot.pdf/png"), "\n")

# ------------------------------------------------------------------------------
# Create visualization - Stacked version by database (Fig 5C)
# ------------------------------------------------------------------------------

# Assign primary category to each pathway (first match only)
assign_category <- function(desc) {
  for (cat_name in names(categories)) {
    patterns <- categories[[cat_name]]
    if (any(sapply(patterns, function(p) grepl(p, desc, ignore.case = TRUE)))) {
      return(cat_name)
    }
  }
  return(NA)
}

sig$Category <- sapply(sig$Description, assign_category)
sig_cat <- sig[!is.na(sig$Category), ]

# Create cross-tabulation
cross_tab <- table(sig_cat$Category, sig_cat$Database)

# Order by total count
totals <- rowSums(cross_tab)
cross_tab <- cross_tab[order(totals, decreasing = TRUE), ]

# Order databases for consistent stacking
db_order <- c("GO_BP", "GO_CC", "GO_MF", "KEGG", "Reactome")
cross_tab <- cross_tab[, db_order[db_order %in% colnames(cross_tab)]]

# Define colors for databases
db_colors <- c(
  "GO_BP" = "#3498db",
  "GO_CC" = "#2ecc71",
  "GO_MF" = "#9b59b6",
  "KEGG" = "#e74c3c",
  "Reactome" = "#f39c12"
)

create_stacked_plot <- function() {
  par(mar = c(5, 12, 4, 8), xpd = TRUE)
  
  barplot(
    t(cross_tab[nrow(cross_tab):1, ]),
    horiz = TRUE,
    las = 1,
    col = db_colors[colnames(cross_tab)],
    border = NA,
    xlim = c(0, max(rowSums(cross_tab)) * 1.05),
    xlab = "Number of Pathways",
    main = "CF-Relevant Pathway Categories by Database",
    cex.names = 0.9,
    cex.lab = 1.1,
    cex.main = 1.2
  )
  
  legend(
    "right",
    inset = c(-0.18, 0),
    legend = colnames(cross_tab),
    fill = db_colors[colnames(cross_tab)],
    border = NA,
    bty = "n",
    cex = 0.9,
    title = "Database"
  )
  
  mtext(paste0("q < ", qvalue_threshold), side = 3, line = 0.3, cex = 0.9, col = "gray40")
}

# Save stacked PDF
pdf(paste0(output_prefix, "_stacked_barplot.pdf"), width = 11, height = 7)
create_stacked_plot()
dev.off()

# Save stacked PNG (Fig 5C)
png(paste0(output_prefix, "_stacked_barplot.png"), width = 11, height = 7, units = "in", res = 300)
create_stacked_plot()
dev.off()

cat("Stacked barplots saved to:", paste0(output_prefix, "_stacked_barplot.pdf/png"), "\n")

# ------------------------------------------------------------------------------
# Create summary table (Table 1)
# ------------------------------------------------------------------------------

summary_df <- data.frame(
  Category = names(category_counts),
  Pathways = as.numeric(category_counts),
  Percent = round(100 * category_counts / nrow(sig), 1),
  stringsAsFactors = FALSE
)

write.csv(summary_df, paste0(output_prefix, "_summary.csv"), row.names = FALSE)
cat("Summary saved to:", paste0(output_prefix, "_summary.csv"), "\n")

cat("\n=== categorize_pathways.R complete ===\n")
